name: Build Go Project

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build
      run: go build -v ./...
    
    - name: Build binary
      run: |
        mkdir -p build
        go build -o build/xuperchain_client_app .
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xuperchain_client_app
        path: build/
