name: Build Go Project

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary_name: xuperchain_client_app_linux
          - os: macos-latest
            goos: darwin
            goarch: amd64
            binary_name: xuperchain_client_app_macos
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Verify Go installation
      run: |
        go version
        which go
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build
      run: go build -v ./...
    
    - name: Build binary
      run: |
        mkdir -p build
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${{ matrix.binary_name }} .
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.binary_name }}
        path: build/
